### ISSUE TITLE
Reporting half the amount.

### ISSUE THREAD

**Issue by Churro-blaze** [MortJC/homebridge-platform-isolarcloud#13]
My solar/lux is reporting half of what the solar is producing. 
Any ideas?

**Comment by MortJC** [comment]
That's weird. Can you send me the debug log?

**Comment by Churro-blaze** [comment]
Sorted now. Operator fault 🤦‍♂️
One of my ubiquity cameras was reporting a lux of 51 for some reason so Apple home was taking an average on the outside lux numbers. 
Thanks for the follow up. 
App working great now.

**Comment by MortJC** [comment]
Good to hear it's resolved.
