### ISSUE TITLE
Troubleshooting 

### ISSUE THREAD

**Issue by EvoSems** [MortJC/homebridge-platform-isolarcloud#2]
Hi. Thanks for your interest in getting isolarcloud on HomeKit. 

I have installed your plugin on my Pi. And have edited the login details. 

Do I have to do anything else? As I cannot get anything to show up in home. 

Are there any other additional steps I need to do? I’m pretty new to homebridge. 

many thanks.

**Comment by MortJC** [comment]
Hi,

I've updated the plugin. Can you please try it again.

Cheers.
