### ISSUE TITLE
Not showing in Home favourites

### ISSUE THREAD

**Issue by 46pixels** [MortJC/homebridge-platform-isolarcloud#7]
I have installed this plug-in and everything seems to work okay however it does not show up in the home favourites at the top. Even though the toggle is on. I've tried it off as well no luck. It shows up in the room okay at the top just not on the Home Screen.

Everything is up to date.

**Comment by MortJC** [comment]
Hi, sorry you can't include it in favorites. Nothing to do with the plug in
itself, it's just the way the Apple Home app works.

**Comment by 46pixels** [comment]
Why is that do you know? Other devices such as temperature do. 

Shame, it’s the only thing I have to go to the room to see the status.

**Comment by MortJC** [comment]
Sorry, don’t know. Question for Apple…
