### ISSUE TITLE
Installed plugin - what should I see in apple home app?

### ISSUE THREAD

**Issue by richardmarr** [MortJC/homebridge-platform-isolarcloud#9]
Installed the plugin - what should I see in the apple home application? Thanks!

**Comment by MortJC** [comment]
In the default room (which I think is study) you should see a light reading
in Lux.

**Comment by richardmarr** [comment]
Thanks - what does the actual figure represent?

Solar power
Power coming in from the grid
?

Thanks
Sent from my iPhone

On 6 Mar 2024, at 5:43 am, James Carvosso ***@***.***> wrote:

﻿

In the default room (which I think is study) you should see a light reading
in Lux.

**Comment by MortJC** [comment]
It should be how much power your system is generating in Watts.

**Comment by richardmarr** [comment]
Perfect thanks
Sent from my iPhone

On 6 Mar 2024, at 8:41 am, James Carvosso ***@***.***> wrote:

﻿

It should be how much power your system is generating in Watts.

**Comment by richardmarr** [comment]
I noticed at night even though solar is not generating anything - it is providing a figure of the kw my battery is feeding the house?
Sent from my iPhone

On 6 Mar 2024, at 11:52 am, Richard Marr ***@***.***> wrote:

﻿ Perfect thanks
Sent from my iPhone

On 6 Mar 2024, at 8:41 am, James Carvosso ***@***.***> wrote:

﻿

It should be how much power your system is generating in Watts.

**Comment by MortJC** [comment]
Not sure. What does the website show?

**Comment by richardmarr** [comment]
![IMG_5090](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/273b6a63-43e6-4ab8-8e10-6d4c63c57b31)
![IMG_5089](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/386facea-333f-443b-af08-0aee4718f916)

see images

**Comment by richardmarr** [comment]
![IMG_5090](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/03b42998-ce99-4966-bbd2-2f50cb4ef411)
![IMG_5089](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/5750dd51-a296-48b6-91d3-42220d269b51)

see above -_^^^ can’t correlate?

**Comment by MortJC** [comment]
What app is that, and from what device does it read?

**Comment by richardmarr** [comment]
The first picture is iSolarCloud via my iPhone. The second photo is the device that Apple home shows for the amount of energy being generated

See this mornings reading

does the reading in Apple home represent

a) the power generated by the solar panels
B) the power consumed by the house
C) the power being delivered or consumed by the battery
D) the power being consumed by or delivered to the grid

![IMG_5095](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/7e3e0e45-98b1-43f2-9026-4854f11c0be8)
![IMG_5094](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/2727beca-1698-46bd-8c9e-fa4b228fbd1d)

**Comment by MortJC** [comment]
What does homebridge say the power is?

There should be a line in the logs like:
[ISolarCloud] Current Power = 4709

**Comment by richardmarr** [comment]
![IMG_5111](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/843bc431-dba7-431a-bd8a-20ca49c2239b)
![IMG_5107](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/43930ed3-ce88-4f99-bc99-309714ca59e5)
![IMG_5109](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/9e70dc86-a47b-48fd-8db8-0e264ce4658d)

getting some error?

**Comment by richardmarr** [comment]
See below note error in logs re to this plugin?
![IMG_5111](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/522f2554-881f-44fb-baf4-3bc76435e312)
![IMG_5109](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/217ad6e7-ffd7-4ea1-b376-c24de4903637)
![IMG_5107](https://github.com/MortJC/homebridge-platform-isolarcloud/assets/26127892/fbde09cb-1edb-4963-a1b0-1d68a1428a17)

**Comment by MortJC** [comment]
Can you please enable debug and send me the logs

**Comment by richardmarr** [comment]
Looks like it is now aligning to power generated from panels!

Will close this for now!

Thank you!
Sent from my iPhone

On 18 Mar 2024, at 9:50 AM, James Carvosso ***@***.***> wrote:

﻿

Can you please enable debug and send me the logs

**Comment by richardmarr** [comment]
Seems to me working fine… probably user error ;)
